# Generated by Django 5.1 on 2025-03-06 10:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('role', models.CharField(choices=[('USER', 'User'), ('ADMIN', 'Admin')], default='USER', max_length=10)),
                ('username', models.CharField(max_length=300, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('password', models.CharField(max_length=300, validators=[django.core.validators.MinLengthValidator(8)])),
                ('ad_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
