# Generated by Django 5.1 on 2025-03-27 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_word_translation_synonym_meaning_favoriteword_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoriteword',
            name='user',
        ),
        migrations.RemoveField(
            model_name='favoriteword',
            name='word',
        ),
        migrations.RemoveField(
            model_name='meaning',
            name='word',
        ),
        migrations.RemoveField(
            model_name='synonym',
            name='word',
        ),
        migrations.RemoveField(
            model_name='translation',
            name='word',
        ),
        migrations.DeleteModel(
            name='Antonym',
        ),
        migrations.DeleteModel(
            name='FavoriteWord',
        ),
        migrations.DeleteModel(
            name='Meaning',
        ),
        migrations.DeleteModel(
            name='Synonym',
        ),
        migrations.DeleteModel(
            name='Translation',
        ),
        migrations.DeleteModel(
            name='Word',
        ),
    ]
