# Generated by Django 5.1 on 2025-03-27 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_words_favoriteword'),
    ]

    operations = [
        migrations.AddField(
            model_name='words',
            name='antonyms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='words',
            name='example_sentence',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='words',
            name='grammatical_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='words',
            name='synonyms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='words',
            name='translation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
